# Generated by Django 4.2.7 on 2024-01-17 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(max_length=255)),
                ('create_user', models.CharField(default='名無しさん', max_length=128)),
                ('file', models.FileField(upload_to='')),
                ('create_time', models.DateTimeField()),
                ('lecture_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.lecturempdel')),
            ],
        ),
    ]
