# Generated by Django 4.2.7 on 2024-01-17 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
