# Generated by Django 4.2.7 on 2024-01-17 11:33

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_alter_uploadmodel_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='lecture_choice',
            field=models.CharField(choices=[('1st', '1回目'), ('2st', '2回目'), ('3st', '3回目'), ('4st', '4回目'), ('5st', '5回目'), ('6st', '6回目'), ('7st', '7回目'), ('8st', '8回目'), ('9st', '9回目'), ('10st', '10回目'), ('11st', '11回目'), ('12st', '12回目'), ('13st', '13回目'), ('14st', '14回目')], default='1st', max_length=200),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='file',
            field=models.FileField(upload_to=upload.models.SavePath),
        ),
    ]
